import type { Combatant } from '~/types'

export const DEFAULT_SETTINGS = {
  isTestData: true,
  dpsType: 'encounter',
  dpsShowDecimals: true,
  theme: 'horiz',
  sortBy: 'dps' as keyof Combatant,
  sortOrder: 'desc' as 'asc' | 'desc',
  prefersReducedMotion: false,
  testRandomizeValuesWithInterval: false,
}
export const TEST_NUMBER_OF_COMBATANTS = 8
export const TEST_NAME_OF_COMBATANTS = [
  'YOU',
  'Doctor Beefcake',
  'Fox Beefcake',
  'Rezelg Lyserg',
  'Edooh Monax',
  'Panda Vlondett',
  'Vivi Ornitier',
  'Yuna Thetuna',
  'Cloud Strife',
  'Squall Leonhart',
  'Warrior of Light',
  'Zidane Tribal',
  'Ramza Beoulve',
  'Caith Sith',
  'Terra Branford',
  'Alphinaud Leveilleur',
  'Alisaie Leveilleur',
  "Y'shtola Rhul",
  'Thancred Waters',
  'Lyse Hext',
  'Urianger Augurelt',
  "G'raha Tia",
  'Estinien Wyrmblood',
  'Krile Mayer Baldesion',
  'Louisoix Leveilleur',
  'Tataru Taru',
  'Minfilia Warde',
  'Yda Hext',
  'Papalymo Totolymo',
  'Arenvald Lentinus',
  'Moenbryda Wilfsunnwyn',
  "A'aba Tia",
  "F'lhaminn Qesh",
  'Arenvald Lentinus',
  'Aenor Cockburne',
  'Aergmhus Saehstymmsyn',
  'Aulie Meulchamps',
  'Alianne Vellegrance',
]
